client:
    container_name: aleac_client
    build: ./
    dockerfile: Dockerfile
    entrypoint: "./entrypoint.sh"
    ports:
        - "3001:3000"
    volumes:
        - ./:/usr/src/app
        - ./logs/npm:/root/.npm/_logs
        - ./package.json:/usr/src/app/package.json